use_frameworks!

target 'LBSwiftModuleDemo_Example' do
  pod 'LBSwiftModuleDemo', :path => '../'

  target 'LBSwiftModuleDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
